### PR TITLE
AUDIO: Added sounds for medieval keys

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---
Added sounds for medieval keys. Three new sounds:
- `misc/medkey.wav` - Picking up the key.
- `doors/medtry.wav` - Failing to open a key door.
- `doors/meduse.wav` - Opening a key door.

### Audio Sample
---
https://github.com/user-attachments/assets/a65c2e18-76ba-4d18-8939-2123b8367cbd

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by lavenderdotpet** [comment]
do u have a hq version of the sound as well

**Comment by Zungrysoft** [comment]
> do u have a hq version of the sound as well

No, I made these in 11025Hz.

**Comment by lavenderdotpet** [comment]
> > do u have a hq version of the sound as well
> 
> No, I made these in 11025Hz.

heard we can prob do the trick that @RandomBrushes uses to make a higher quality version 

we eventually are gonna have the sound quality set by the build system

**Comment by lavenderdotpet** [comment]
make sure to add Ur self to the credits of sounds u can do that to

**Review by Nolcoz — COMMENTED** [review]
Checked the metadata for the sounds, and noticed that some have the year of 1996.

**Comment by lavenderdotpet** [comment]
> Checked the metadata for the sounds, and noticed that some have the year of 1996.

I believe that's a default in some editors

**Review by Nolcoz — APPROVED** [review]
Its good then

**Review by lavenderdotpet — APPROVED** [review]
:sound: sounds good to me

**Comment by lavenderdotpet** [comment]
@Zungrysoft merge when ur ready

**Pull request merged**
