### PR TITLE
BUILD, MAP: Removed missing textures from a bunch of map files.

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---
Removed all uses of `hp25_side` texture from the megahealth brush model to get rid of compiler warnings.

### Visual Sample
---
N/A

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [x] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by Zungrysoft** [comment]
Weird. It's failing with `WARNING: unable to find texture skip` on `b_bh10_lite.map`, but that map doesn't have any skip textures in it. It's not failing on any of the other bmodels as far as I can tell.

**Comment by Zungrysoft** [comment]
Okay, it's only failing on bmodels which don't use `lq_dev.wad`. So I've added that WAD to the failing bmodels.

**Review by pnahratow — APPROVED** [review]
Thanks for the fixes

**Review by lavenderdotpet — APPROVED** [review]

**Comment by lavenderdotpet** [comment]
@Zungrysoft merge when Ur ready

**Pull request merged**
