### PR TITLE
Tweaked udeath

### PR DESCRIPTION
**Pull request by Ogrobastard**
Modified version of existing "udeath" by user "Ospaggi", as originally posted in LibreQuake discord channel "audio-music".
Second attempt of sending the file after merging the latest main.

### Description of Changes
---
Using Audacity, I've reversed the original sample and made a small trim to remove repetitive noises.

### Visual Sample
---
373906119-9dfda5d3-b1b6-4dd8-b4c9-42ee2fbfb0f3

### Checklist
---

- [X] I have read the LibreQuake contribution guidelines
- [X] I have thoroughly tested my changes to the best of my ability
- [X] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by MotoLegacy** [comment]
I've unchecked "critical" as this is not a critical issue. Also, be mindful next week that contribution guidelines will be enforced.

**Review by MotoLegacy — APPROVED** [review]

**Comment by Ogrobastard** [comment]
> I've unchecked "critical" as this is not a critical issue. Also, be mindful next week that contribution guidelines will be enforced.

Sorry 'bout that, thought it was one of the problems that gave me problems with the first pull request. Will "not check" next time! ;)

**Comment by lavenderdotpet** [comment]
what does the meta data look like

**Review by Zungrysoft — APPROVED** [review]

**Comment by Ogrobastard** [comment]
> what does the meta data look like

[udeath.json](https://github.com/user-attachments/files/17357221/udeath.json)
Didn't make modifications to it, just the audio file itself.

**Comment by lavenderdotpet** [comment]
> > what does the meta data look like
> 
> [udeath.json](https://github.com/user-attachments/files/17357221/udeath.json)
> Didn't make modifications to it, just the audio file itself.
> 

well there should be a modification to it
make sure to add Ur credits to the author list

**Review by MotoLegacy — DISMISSED** [review]
Marking as needs work since Lav requested changes but did not submit this request.

**Review by lavenderdotpet — APPROVED** [review]
gonna go ahead and approve this 
with the audio index being a thing 
meta data is less of an issue

**Pull request merged**
