### PR TITLE
MAPS: Updated start map with skill select and more

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---

Updated the start map to have all of the things a start map should. (As well as a few LQ-specific things.) This is purely a functional update. The map is still undetailed and temp, obviously. Hopefully this can be used as a template for the completed start map, whenever that gets made.

- Added skill select (including a separate hallway for Nightmare)
- Moved dev teleporter further back to make it harder to go into accidentally.
- Moved Episode 0 gate to a separate hallway.
- Locked Episode 0 gate until the player has collected at least one rune. (This is a technical requirement. If the player returns to the start map without having collected any runes, the game will not take away their weapons. Since Episode 0 doesn't have a rune, the solution is to prevent the player from entering the episode until they have one.)
- Added end map gate which is locked until the player has collected every rune.
- Added `func_episodegate` entities to the gates to prevent the player from accidentally re-entering episodes they have already completed.
- Added a deathmatch episode gate. It only appears in deathmatch and links to lqdm1.
- Added coop and deathmatch spawns.
- Added info_player_start2.
- Added intermission cam. (For deathmatch)
- Added map name. ("Episode Select")

### Visual Sample
---
fte-20241107230505-0
fte-20241107201420-0
fte-20241107201424-0
fte-20241107201431-0
fte-20241107201438-0

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [x] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by Zungrysoft** [comment]
Marked as critical because I would like to get this into the next release.

**Comment by lavenderdotpet** [comment]
I don't like that episode 0 is locked behind a rune

**Comment by lavenderdotpet** [comment]
also why get rid of the coloured lights from the portals

**Comment by Zungrysoft** [comment]
> I don't like that episode 0 is locked behind a rune
> is there no way to take a way the weapons?
> maybe just move episode to the right end

No way that I can find. The game checks if the map is start and that player has at least one rune. As far as I know, there is no other way to take away the player's items in the vanilla progs.

**Comment by Zungrysoft** [comment]
> also why get rid of the coloured lights from the portals

Whoops. That was a mistake. I've reverted that change.

**Comment by Zungrysoft** [comment]
> hmm I rather it just be at the end after 4 then

So you want me to lock it behind the same gate as the end map?

**Comment by lavenderdotpet** [comment]
> > hmm I rather it just be at the end after 4 then
> 
> So you want me to lock it behind the same gate as the end map?

no like unlocked and just placed next to the 4 portal maybe also replace the 0 with win or dos

**Comment by Zungrysoft** [comment]
> no like unlocked and just placed next to the 4 portal maybe also replace the 0 with win or dos

Well that doesn't solve the problem. If the portal is unlocked, the player could still choose to play that episode first and then go into another episode with every single weapon unlocked, which those episodes were not balanced for. It would be a confusing thing the for the player if they got to keep all of their weapons the first time they moved to the next episode, but didn't get to keep their weapons any other time.

**Review by Nolcoz — APPROVED** [review]
I think its good. I think its better this way were you only need one rune for e0 instead of 4. It is kinda sad we cant have it so you could do e0 first.

**Review by RandomBrushes — APPROVED** [review]
Looks, indeed, good to me

**Comment by lavenderdotpet** [comment]
oh @RandomBrushes i wanted to test this out first

**Comment by RandomBrushes** [comment]
> oh @RandomBrushes i wanted to test this out first its fine tho

Oh, sorry, I didn't notice your earlier comment.

**Pull request merged**
