### PR TITLE
New concrete textures

### PR DESCRIPTION
**Pull request by Nolcoz**
Concrete textures meant for tech wad, with multiple variations in color and materials(7 types of walls and 2 types of floor textures).
Here is a pic of them in wad.

EDIT:
These textures are now in a separte folder called lq_conc. The wad compiler was also modified so it also takes into account this folder

Captura de pantalla (35)
Captura de pantalla (36)
Captura de pantalla (37)

And some of them in game

spasm0060
spasm0062
spasm0063

### CODE REVIEW

**Comment by MissLavender-LQ** [comment]
honestly theres enough here for it to be its own wad if u want to move it to its own

**Comment by MissLavender-LQ** [comment]
just make sure to add it to these scripts
https://github.com/MissLavender-LQ/LibreQuake/blob/main/texture-wads%2Fcompilewads.sh
https://github.com/MissLavender-LQ/LibreQuake/blob/main/texture-wads%2Fcompile_wads.py

**Comment by Nolcoz** [comment]
Gonna be honest, can I do that later, not on this day? I am not as sick as
before but I am still damn tired and even if its really easy to do, I
really dont feel like it right now.

**Comment by MissLavender-LQ** [comment]
yeah thsts fine never feel any rush to do things right a way rest and take ur time
i could do it if need be when i have the ability

**Comment by Nolcoz** [comment]
If you want to do that, I am fine with that

**Comment by MotoLegacy** [comment]
@MissLavender-LQ could you please conduct a proper review so the PR reflects the "Changes Requested" status? It can be blank, it is just important that the status is reflected properly.

**Review by MissLavender-LQ — CHANGES_REQUESTED** [review]
na

**Comment by MissLavender-LQ** [comment]
> honestly theres enough here for it to be its own wad if u want to move it to its own

disregard after looking at it i think it should stay in lq_tech

**Review by MissLavender-LQ — APPROVED** [review]
lgtm

**Review by MotoLegacy — APPROVED** [review]
Definitely a lot of textures here that I'd personally consider making their own WAD. But since Lav has disagreed with this notion it otherwise looks fine.

**Comment by Nolcoz** [comment]
Moved the conc textures files out of lq_tech and into a seperate folder called lq_conc

**Comment by MissLavender-LQ** [comment]
> Moved the conc textures files out of lq_tech and into a seperate folder called lq_conc

looks good to me I'll update the script later if u don't want to

**Comment by NicoOlcoz** [comment]
> looks good to me I'll update the script later if u don't want to

K then, no problem with that

**Comment by Nolcoz** [comment]
> looks good to me I'll update the script later if u don't want to

K then, no problem with that

**Comment by Nolcoz** [comment]
Edited the original post so that it now says that the concrete textures now go in a separet folder than the tech one

**Pull request merged**
