### PR TITLE
MAPS: fix for the build issues by removing sky-test from use in maps

### PR DESCRIPTION
**Pull request by lavenderdotpet**
### Description of Changes
---
replaces sky-test why sky_pando the proper texture which fixes the build issues we have been having

this fix was a part of [this pull request](https://github.com/lavenderdotpet/LibreQuake/pull/130) but now has been separated to since more changes were requested on that side that was stalling this fix from being applied 

### Visual Sample
---
image

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [x] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by Zungrysoft** [comment]
The build is still failing since I merged e1m4 which uses textures from https://github.com/lavenderdotpet/LibreQuake/pull/183. If you review and approve that PR, I can merge it and that will solve this.

**Comment by MotoLegacy** [comment]
I am confused over the coordination here. Is this PR required or is there another PR that is also resolving this same build failure? Please communicate, thanks

**Comment by lavenderdotpet** [comment]
> The build is still failing since I merged e1m4 which uses textures from #183. If you review and approve that PR, I can merge it and that will solve this.


you aren't using sky-test at all are ya?

**Comment by Zungrysoft** [comment]
@lavenderdotpet You'll have to merge master back into this branch to get it to pass the checks now.

**Review by Zungrysoft — APPROVED** [review]

**Review by Nolcoz — APPROVED** [review]

**Pull request merged**
