### PR TITLE
GFX : fixed font shadow overlapping other characters 

### PR DESCRIPTION
**Pull request by lavenderdotpet**
## note
this is a fix for this issue https://github.com/lavenderdotpet/LibreQuake/issues/166

## Description of Changes

fixed the conchar font files k and ~ by moving over most of the chars to the left by one pixel (moved all of them over to not mess up the spacing of characters)

## Visual Sample

conchar
conchar

## Checklist

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by lavenderdotpet** [comment]
test to see if the webhook is working

**Review by MotoLegacy — APPROVED** [review]
Thanks!

**Review by pnahratow — APPROVED** [review]
:+1: as I see this the dead pixel came from the J right?

**Comment by lavenderdotpet** [comment]
> :+1: as I see this the dead pixel came from the J right?

yeah that can be seen on the issue I link to

**Pull request merged**
