### PR TITLE
new ogre design

### PR DESCRIPTION
**Pull request by lavenderdotpet**
update to the newer ogre model
still not animated or textured but is easier then the old model so will improve readability till we can finish the design
image

### CODE REVIEW

**Comment by lavenderdotpet** [comment]
image
old model

**Comment by lavenderdotpet** [comment]
https://github.com/user-attachments/assets/7a45b240-20fb-453e-8b1a-92b90baaf2e4

temp animations by @Nolcoz

**Review by Nolcoz — APPROVED** [review]
Works well, yeah
dev_2024-07-25_14-36-53

**Review by Mr-M818 — APPROVED** [review]
approve

**Pull request merged**
