### PR TITLE
MAPS, WADS: Fixed sky_test error in ericw tools

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---
Fixed a CI error with sky_test giving a warning about a missing texture. Replacing the hyphen with an underscore fixes this for some reason.

### Checklist
---

- [ ] I have read the LibreQuake contribution guidelines
- [ ] I have thoroughly tested my changes to the best of my ability
- [ ] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by lavenderdotpet** [comment]
just remove the texture and replace the name with the proper one that file was only made when I was testing some stuff

**Comment by lavenderdotpet** [comment]
or I'll take care of it when I wake up

**Comment by Zungrysoft** [comment]
> the work is already done on the branch I just have to move it to a new pull req when I get back to my pc in the morning

Alright. That sounds good. Though the CI is still failing and I have no idea why.

**Comment by lavenderdotpet** [comment]
https://github.com/lavenderdotpet/LibreQuake/pull/130



it's fine here

**Pull request closed without merging**
