### PR TITLE
Fix map build errors and add the build workflow to pull requests

### PR DESCRIPTION
**Pull request by pnahratow**
## Description

We noticed during the build process failures get silently ignored. e1m2 was lit as fullbright. The `light` step actually failed because of a faulty light with `delay: 15`

This change will make the build process fail whenever a shell command fails and then the error is printed. This way we will catch errors like the one with e1m2 from now on.

I fixed e1m2 but also had errors on the brushmodels because most of them would fail the vis stage.

From what I understand the vis process fails for brushmodels that have lights in them. Probably because the maps are not enclosed. There is one model `b_batt1` that has lights but doesn't fail. The model here is a `func_detail_wall` so maybe there is something to that. I am not a mapper so maybe this can be resolved differently.

The way I have resolved this now is that I added a method to skip steps by adding the value `LQ_SKIP` to the compile flags. I added this to all the configs that failed the vis stage.

With that there was also some refactoring

## Changes

- Replace all subprocess calls with the same construct that checks the return code and fails with a message if necessary
- Refactor unused execute_command in compile_maps.py to use that same pattern
- Remove unused `LQ_MAP_SRC_PATH`
- Remove global variable shenanigans for compile flags
- Retrieve config paths without using hardcoded values like that horrible `f"{path[6:-4]}.conf"`
- Read config to a dictionary in a generic manner
- Skip vis or light when the `LQ_SKIP` value is present in the compile flags
- Add `LQ_SKIP` to the vis flags of all brushmodels that failed vis

### CODE REVIEW

**Comment by MotoLegacy** [comment]
Thanks for this. Seems to look good to me. Any chance we could have PR test builds moving forward now that we'll be reaching the failure state correctly?

**Comment by pnahratow** [comment]
@Nolcoz @Mr-M818 @Zungrysoft not sure who of you knows best how these brushmodels work or are supposed to work. But can you look at the vis problem I described in this MR description and answer the following questions

- Should we skip VIS for the failing brushmodel maps like I have proposed here or
- Should the brushmodels all be `func_detail_wall` or some other brush entity to maybe not fail VIS
- Should the brushmodels that don't have any lights defined get some like the other brushmodels

**Comment by Nolcoz** [comment]
Checked the brushmodels in game after running the script for compiling them (as in the one in the main repo, not this one) and they all seem to be properly lit
spasm0001

- The way the brushmodels work from what I get is that in the base game they all have lights in the map file so that diferent sides of the box are lit diferent. So esentially those models can not be VISed at all.
With the exception of:
 b_bh10_lite
 b_bh25_lite
 b_bh100_lite
 b_exbox2
 b_explob
The rest are all func_detail_wall. To be honest I am not sure if them being func_detail_wall or not makes a diference in performance but I think it doesnt make a diference in terms of VIS, as the lights are not contained in both cases.

So yeah, all this to say that I think for the brushmodels should be skipped in terms of VIS, so it doesnt fail compiling. They cant pass VIS in the first place in the original game.

- As for having all brushmodels have lights I do think its a nice aesthetic feature the other ones could have. Its a good way to make them not look as flat

Also I dont know if you implemented the skipping the brushmodels in terms of VIS in your pull, because I downloaded and it seems to stop compiling after b_batt0_lite.

**Comment by pnahratow** [comment]
@Nolcoz thanks for testing. I have now set all the brushmodels to skip vis. Initially I only had the ones that failed for me. Maybe on your system it is different. But with your comments I am confident that it makes sense to generally skip that.

@MotoLegacy I have enabled the build pipeline for pull requests as you suggested. It is even visible here directly. 
with that we should maybe edit something so the github bot in discord doesn't spam about each job activity @lavenderdotpet 

Other that the change is ready from my side and can be merged if okay.

**Review by lavenderdotpet — APPROVED** [review]
looks good to me but ill wait for @MotoLegacy and @Nolcoz to have a chance to respond before merging

**Comment by Nolcoz** [comment]
Downloaded your build and when I try to run build.py, it just throws this error. Not sure exactly what the problem is 
Captura de pantalla (136)

**Comment by pnahratow** [comment]
@Nolcoz that seems like it wasn't done with the most recent version of this branch. Try to `git pull` on the branch and see if the error persists

**Review by Nolcoz — APPROVED** [review]
Compiled it and all seems to be working fine

**Comment by MotoLegacy** [comment]
Merging this as it's been sitting for a few days with multiple approvals.

**Pull request merged**
