### PR TITLE
GFX: Fix colormap having incorrect fullbright count

### PR DESCRIPTION
**Pull request by lavenderdotpet**
https: //discord.com/channels/464531227509260291/491346068886519828/1274258963222892545
image

### broken
broken
### fixed
fixed

### CODE REVIEW

**Comment by MotoLegacy** [comment]
Awesome, a good catch. Can you change your commit message to provide detail about what the fix REALLY is though? Something like,

GFX: Fix colormap having incorrect fullbright count

It's important when writing commit messages to provide something tangible but not overly verbose.

Additionally, we should probably generate the colormap as part of a build script. Can you open an issue requesting this? Not a PR blocker, but nice to have.

**Review by MotoLegacy — CHANGES_REQUESTED** [review]
See above comment

**Comment by lavenderdotpet** [comment]
> See above comment

thank u good catch and thanks for the advice

**Review by MotoLegacy — CHANGES_REQUESTED** [review]
Hi Lav, it looks like you only changed the PR title, not the commit message. Prior review still stands :)

**Comment by lavenderdotpet** [comment]
> Hi Lav, it looks like you only changed the PR title, not the commit message. Prior review still stands :)

hi im unsure how to update the commit msg

**Comment by MotoLegacy** [comment]
That's fine then, no worries since we are not yet enforcing our condition guide

**Review by MotoLegacy — APPROVED** [review]

**Pull request merged**
