### PR TITLE
[WADS] hp25_side missing texture fix

### PR DESCRIPTION
**Pull request by lavenderdotpet**
added hp25_side to fix missing texture error

### Description of Changes
---
added hp25_side to fix missing texture error 
is only used on the inside faces of some of the hp bmodels 

### Visual Sample
---
heres a screenshot of said texture 16x16 scaled up by 10
image

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [x] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by MotoLegacy** [comment]
I've checked the "critical" box for you as this fixes build failure.

**Comment by lavenderdotpet** [comment]
> I've checked the "critical" box for you as this fixes build failure.

fair and thanks

**Comment by lavenderdotpet** [comment]
image
@pnahratow im not sure what exactly is failing here 
what texture is it referring to

**Comment by pnahratow** [comment]
@lavenderdotpet it says if you scoll up a bit. Its missing `skip` in `b_bh10_lite.map`

**Comment by Zungrysoft** [comment]
Wouldn't it be better to just change the brush model to no longer use the missing texture? Then you don't have to add a new texture that will never get seen.

**Comment by Zungrysoft** [comment]
I've opened a separate PR that fixes this issue by removing usages of the missing texture.

**Comment by lavenderdotpet** [comment]
closing this pull req due to this one superseding it https://github.com/lavenderdotpet/LibreQuake/pull/177

**Pull request closed without merging**
