### PR TITLE
GFX: Fixed coloring on weapon selection HUD

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---
Fixed coloring on weapon selection HUD to use the newer color scheme. When I originally created that section of the HUD, I made it based on an older, outdated version of the HUD.

### Visual Sample
---
See "Files changed" for visual difference.

image

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by lavenderdotpet** [comment]
an image of the fully equipped bar would work for the image section

**Comment by lavenderdotpet** [comment]
ah shoot the key ui is still yellow

**Comment by Zungrysoft** [comment]
> ah shoot the key ui is still yellow

Fixed

**Review by lavenderdotpet — APPROVED** [review]

**Review by Nolcoz — APPROVED** [review]
All good here

**Pull request merged**
