### PR TITLE
MAPS, WADS: New e1m4 replacement: Dismal Shores

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---
Introduces the replacement for e1m4 called Dismal Shores. This crumbling seaside castle contains challenging combat and four hidden crystals which must be found to unlock the Episode 1 secret level.

Also added new textures for this level.

### Visual Sample
---
fte-20241011180949-0
fte-20241011175756-0
fte-20241011175817-0
fte-20241011175829-0
fte-20241011175845-0
fte-20241011175910-0
fte-20241011180015-0
fte-20241011180040-0
fte-20241011180057-0

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by Zungrysoft** [comment]
I'm not sure why the CI is failing. e1m2 is getting a missing texture error from `sky-test`, but it's definitely in the repo and was not touched by this PR.

**Comment by lavenderdotpet** [comment]
image
yeah no sky test in the map either

**Comment by lavenderdotpet** [comment]
image
failing on e2m1 which does have sky-test

**Comment by lavenderdotpet** [comment]
ah i think i might know what the issue is 
all the skys are sky_ sky-test is the only one that has the - which might be causing issues

**Comment by lavenderdotpet** [comment]
this is partly connected to my unfinished work over on this pull req https://github.com/lavenderdotpet/LibreQuake/pull/130

**Review by lavenderdotpet — APPROVED** [review]

**Comment by Nolcoz** [comment]
One thing I noticed from replaying is that the secret for the purple cristal is diferent now, and I think its harder to find now(with how it involves looking up in a place that seems to have nothing). The only reason I found it is because I knew it was there. Maybe you could keep the secret button there if it was more obvious that there is a door that can be opened there, making it so the player is incetivised to look for the button in that room.
Apart from that its all good, just waiting on your opinion of that to approve. If you wanna keep it, its fair

**Comment by Zungrysoft** [comment]
@Nolcoz One of the things I changed from the playtest version is that all four of the crystal secrets now use a specific texture on the door that hints that there is a secret crystal behind it. If you pick up on this pattern, you can know that there is a secret switch somewhere in that room.

fte-20241012101717-0
fte-20241012101634-0
fte-20241012101647-0
fte-20241012101654-0

**Review by Nolcoz — APPROVED** [review]
Ahhh I see I see. Didnt catch on that.
K then, seems good to me then

**Comment by lavenderdotpet** [comment]
@Zungrysoft once we hit 24 hrs feel free to merge 

also 
tomorrow I'll separate the sky-test fox from the sky pull req so this build issue is fixed

**Pull request merged**
