### PR TITLE
MODELS : updated texture for the vore/shalrath replacment

### PR DESCRIPTION
**Pull request by lavenderdotpet**
# Description of Changes

### new vore texture done by me in substance painter

# Visual Sample

### left old | right new
image

# Checklist

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

- note ignore the branch name, cant update it now and the contributions stuff hasn't merged yet so not required but am using this pull req to learn it as of typing this reading it

### CODE REVIEW

**Review by Zungrysoft — APPROVED** [review]

**Review by Nolcoz — APPROVED** [review]
Tested it, and yeah it looks good

**Comment by lavenderdotpet** [comment]
once 24 hrs pass ill add ill merge this

**Review by MotoLegacy — APPROVED** [review]
Good work!

**Review by pnahratow — APPROVED** [review]
:+1:

**Pull request merged**
