### PR TITLE
MAPS, WADS: Reworked e1m1

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---
Significantly overhauled e1m1. Previously, e1m1 was too similar to the original game's e1m1, which set up an expectation that LibreQuake's singleplayer campaign was mostly just going to re-tread the same ground as the original game's campaign. Working with @RandomBrushes and @adaya, I have replaced several areas in the level with brand new combat. This PR also contains changes from @RandomBrushes, who made a bunch of detailing improvements to the map as well.

Changelog:
- Completely overhauled the first few combat encounters.
- Overhauled the Nailgun encounter.
- Changed the Double-Barelled Shotgun encounter by making the entire upper deck of the jail a secret area.
- Added force fields to the enemies on the upper deck. (credit: @RandomBrushes)
- Removed teleported enemies in the final encounter.
- New secrets and modifications to existing ones.
- Fixed unused intermission cams by making intermission cams depend on the number of found secrets.
- Minor gameplay tweaks to existing areas.
- Lots of lighting and texture adjustments. (credit: Myself and @RandomBrushes)
- Deathmatch support

### Visual Sample
---
#### Your view upon starting the level:
fte-20241017010746-0

#### The train station:
fte-20241017010806-0
fte-20241017010811-0

#### The first combat encounter
fte-20241017010829-0

#### The trainyard
fte-20241017010843-0
fte-20241017010854-0
fte-20241017010903-0

#### The new nailgun area
fte-20241017010923-0

#### Shotgun force-fields
fte-20241017011010-0

#### Acid tunnel
fte-20241017011032-0

#### Shortcut back to the start
fte-20241017011101-0

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by RandomBrushes** [comment]
The build fails due to

`WARNING: unable to find texture sky-test`

**Comment by lavenderdotpet** [comment]
> The build fails due to
> 
> `WARNING: unable to find texture sky-test`


approve this https://github.com/lavenderdotpet/LibreQuake/pull/188

**Review by Nolcoz — APPROVED** [review]
Its really good, ye

**Review by RandomBrushes — APPROVED** [review]
Looks good to me :-)

**Pull request merged**
