### PR TITLE
Add zom_gib.mdl

### PR DESCRIPTION
**Pull request by pnahratow**
This is a super basic model

here is the original quake model
original

here the one I recreated
new_one

### CODE REVIEW

**Comment by MissLavender-LQ** [comment]
love that u post images
oh! also is that lunarviewer

**Comment by pnahratow** [comment]
Yes I got it running with the info you provided

**Comment by MissLavender-LQ** [comment]
this maybe should be considered temp but yea works and lgtm

**Review by MissLavender-LQ — COMMENTED** [review]
👍

**Comment by MotoLegacy** [comment]
> this maybe should be considered temp but yea works and lgtm 
> 

Why exactly? Helps me judge my review. It's not good practice to push temporary assets in certain contexts

**Comment by MissLavender-LQ** [comment]
> Why exactly? Helps me judge my review. It's not good practice to push temporary assets in certain contexts

because i could work on it later to get it to better match gib1 gib2 gib3's texture style

**Comment by pnahratow** [comment]
It won't hurt my feelings if this gets rejected. This is really just a low effort attempt at making more of the placeholder signs go away.

**Comment by Zungrysoft** [comment]
I say this works just fine even if it is temp. If someone wants to replace it later with a more fitting asset, there's nothing stopping us. This is at least better than the placeholder sign.

**Review by Zungrysoft — APPROVED** [review]

**Review by lavenderdotpet — APPROVED** [review]

**Pull request merged**
