### PR TITLE
Update lq_dev_readme.txt

### PR DESCRIPTION
**Pull request by lavenderdotpet**

### CODE REVIEW

**Review by Zungrysoft — APPROVED** [review]

**Review by MotoLegacy — CHANGES_REQUESTED** [review]
Please use a more descriptive commit message.

**Comment by Zungrysoft** [comment]
@MotoLegacy Lmao it's a one-line change that affects nothing. I don't think we need to block the PR for something like this.

@lavenderdotpet Just be a little bit more descriptive in the message when you squash and merge.

**Comment by lavenderdotpet** [comment]
i didnt think any extra info was needed due to title and it being a single line u can see just from the file changed section

**Comment by MotoLegacy** [comment]
Sure thing, just keep in mind writing imformative commit messages is something we want to standardize doing in the future

**Review by MotoLegacy — APPROVED** [review]

**Pull request merged**
