### PR TITLE
MAPS, WADS: New e1m5 replacement: Gloomliths

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---
Introduces a new replacement for e1m5 called Gloomliths. Taking place within the winding halls of two monolithic black stone structures, this map has tons of secrets and puzzles to unlock secret items and alternate paths. There is in fact an entire second path through the level you can access right from the start.

Also added new textures for this level.

This replaces the previous e1m5 map Reading of the Dead. I have moved it into the Episode 1 archive folder for now.

### Visual Sample
---
fte-20241001230137-0
fte-20241001230150-0
fte-20241001230204-0
fte-20241001230233-0
fte-20241001230258-0
fte-20241001230309-0
fte-20241001230319-0
fte-20241001230333-0

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Review by Nolcoz — CHANGES_REQUESTED** [review]
After compiling the map with the branch, it seems that at the start there is a missing texture here.
e1m5_2024-10-02_22-51-12
Apart from that, everything seems fine

**Comment by MotoLegacy** [comment]
> After compiling the map with the branch, it seems that at the start there is a missing texture here. e1m5_2024-10-02_22-51-12 Apart from that, everything seems fine

Weird, our CI should've flagged this. @pnahratow can you investigate?

**Comment by Zungrysoft** [comment]
@Nolcoz Whoops. I just fixed it.

**Review by Nolcoz — APPROVED** [review]
Yep, fixed
e1m5_2024-10-03_01-05-17

**Comment by pnahratow** [comment]
> Weird, our CI should've flagged this. @pnahratow can you investigate?

It shows a warning. My guess is that the warning doesn't make qbsp fail. I could either try to find out if there is some `fail-on-warnings` in ericw-qbsp or I could parse for the `WARNING` string manually.

**Comment by lavenderdotpet** [comment]
> > Weird, our CI should've flagged this. @pnahratow can you investigate?
> 
> It shows a warning. My guess is that the warning doesn't make qbsp fail. I could either try to find out if there is some `fail-on-warnings` in ericw-qbsp or I could parse for the `WARNING` string manually.

could maybe do a qbsp | grep "warning" and some how out put that to the git build process

**Comment by MotoLegacy** [comment]
> > Weird, our CI should've flagged this. @pnahratow can you investigate?
> 
> It shows a warning. My guess is that the warning doesn't make qbsp fail. I could either try to find out if there is some `fail-on-warnings` in ericw-qbsp or I could parse for the `WARNING` string manually.

Thanks for taking a look. Can I assign an issue to you for this?

**Comment by RandomBrushes** [comment]
Also had a playthrough. It's a very fine map that fits the other e1-maps better than the current e1m5.

As usual, I didn't find any secrets and thus missed half the enemies, but surprisingly didn't get lost.

Visually, I guess some parts are looking very blocky and that gray stone wall texture is really carrying most of the structual load, but the mood is excellent and I guess some visual palette cleaners can be integrated later on.

I'd say things are very merge-able.

**Comment by pnahratow** [comment]
> > > Weird, our CI should've flagged this. @pnahratow can you investigate?
> > 
> > 
> > It shows a warning. My guess is that the warning doesn't make qbsp fail. I could either try to find out if there is some `fail-on-warnings` in ericw-qbsp or I could parse for the `WARNING` string manually.
> 
> Thanks for taking a look. Can I assign an issue to you for this?

No

https://github.com/lavenderdotpet/LibreQuake/pull/174

**Comment by lavenderdotpet** [comment]
this ready to merge?

**Pull request merged**
