### PR TITLE
MAPS: Softened lightstyles in E1M1

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---
Softened lightstyles in E1M1 on @lavenderdotpet 's request.

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by RandomBrushes** [comment]
In principle, this looks good to me. However, I still see high-contrast flickering in the acid tunnel and in some prison cells. I guess Lav will have to comment on whether that's within acceptable limits.

**Comment by lavenderdotpet** [comment]
I'll check it soon

**Comment by lavenderdotpet** [comment]
https://github.com/user-attachments/assets/1339153a-ed30-4eea-a9b2-d9ef6d6a2ad0

this flashing is still way to much i think @RandomBrushes's take on it was better 
sorry i forgot to check it on ur version before

**Comment by lavenderdotpet** [comment]
1 sec working on something for this

**Comment by lavenderdotpet** [comment]
https://github.com/user-attachments/assets/510b266e-91d4-455f-a8b5-8ef83ace190e

**Comment by lavenderdotpet** [comment]
i probably shouldn't approve of it now that i've made changes 
@RandomBrushes feel free to approve/review

**Comment by lavenderdotpet** [comment]
nothing with progs was changed why is it failing??? 
why is there a library missing???

**Comment by RandomBrushes** [comment]
This looks good to me, but I'm a bit confused regarding the scope of the changes. As far as I can see, only the flickering light in the starting area seems to have been edited, while e.g. the acid-tunnel and the prison cells still have high-contrast flickering. Are those okay as-is?

**Comment by lavenderdotpet** [comment]
> This looks good to me, but I'm a bit confused regarding the scope of the changes. As far as I can see, lights near the starting area seem to have been edited, while e.g. the acid-tunnel and the prison cells still have high-contrast flickering. Are those okay as-is?

oh I missed those ill check them

**Review by lavenderdotpet — APPROVED** [review]
there are some more changes that need to be addressed here but were trying to get a release out so the other changes will be addresses in a new pull request later on

**Review by RandomBrushes — APPROVED** [review]
Further changes may be needed in the future (there are still some high-contrast flickering lights), but this is an improvement over the current state.

**Pull request merged**
