### PR TITLE
MAPS, WADS: Added e3m6 

### PR DESCRIPTION
**Pull request by Nolcoz**
### Description of Changes
---
Adds an e3m6, the final map of the episode, mostly focused on arena fights involving Vores.
Because of the really open space the map has(involving the corpse set piece) the map can take quite a while to compile, even then it can still compile.
The textures on the corpse are placeholders so bear that in mind.

New greek and flesh textures have also been added, with the greek ones expanding the blue theme, while the flesh textures are mostly darker rotting variants of flesh textures, along with ones combining wood.

### Visual Sample
---
e3m6_2024-10-20_21-03-18
e3m6_2024-10-20_21-03-49
e3m6_2024-10-20_21-04-48

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by Nolcoz** [comment]
>I'm not a fan of the wood-embedded flesh textures. I think it would look much better if you built actual physical beams using brushwork rather than relying on the texture to do the work for you. It feels like something you would do in a Doom level, not in Quake.

The reason I made the wood part of texture is mostly to optimise it and tbh was easier to put down than making wooden beams for every sloped wall. I could maybe push the detaling fuether tbh but I am not sure if its pushing it too far with detailing

>The bit at the end with the vores just confuses me. They can't hurt you because of the shroud put over them. And if you ran out of ammo, you have to very slowly hack them to death. What is the purpose?

Soooo I didnt test it in FTEQW. Final sequence is broken in fteqw it seems. They are supposed to get crushed by the platforms and die instantly but it seems that doesnt happen and instead they get stuck inside of it.

>The trigger_push at the end rockets you out too fast so you can't actually tell what's happening until it's over. I think it would be better so send the player at a slower speed but a higher angle so you can watch as you fly through the air.

Ye, thats true. That part was very much a last addition thing, that I never really bothered to change. I can change it so it goes slower

>If you watch the demo, the final vore on the platform didn't end up on the platform; it just got stuck in the water. It might be another FTEQW-specific bug.

Yep, its an fteqw thing. Doesnt happen in other ports.

Also, as for taking so long to compile I have managed to squezee some compiling time out by using more func_details. I still have to work on that a lil more so its gonna take a while

**Comment by Zungrysoft** [comment]
@Nolcoz For the sloped walls, I can kind of understand it since that would be a pain with how much you used the crossbeam texture. I do still think it would look much nicer with actual depth and the shadows. So I think you should at least do real beams for the flat walls.

Like this room. I think 3D beams here would add a lot of depth and interest to the scene.
fte-20241023004351-0

**Comment by lavenderdotpet** [comment]
or do we have an e3m7/secret map or one planned?

**Comment by Nolcoz** [comment]
>@Nolcoz For the sloped walls, I can kind of understand it since that would be a pain with how much you used the crossbeam texture. I do still think it would look much nicer with actual depth and the shadows. So I think you should at least do real beams for the flat walls.

After some testing, tbh adding brush beams doesnt really add much, as they are gonna be func_details and not cast much shadows, because other wise they would be really annoying and also I dont really have much space to push back the wall brushes
spasm0001

Altought this compromise of some parts being brushes on top of the wood texture is kinda nice tbh
spasm0002

**Comment by Nolcoz** [comment]
@Zungrysoft So after checking what is up with the ending of the map involving the crushers and the vores, the glitch seems less like a glitch in my map and more of FTEQW and how it handles crushers.

Okay, so here is the original problem with crushers, on the same map (I did make the platform closest to the rune bigger to test if it changed anything and it did nothing)
https://youtu.be/GMqW5dulfcA

Then is me coping the exact same setup from that map into an empty new one
https://youtu.be/s3FX3j13d7A

And then is a recreation from scratch of how crushers work
https://youtu.be/YqsMaoSrboo

I guess I can change that to be a func_train instead, but it seems more of a problem with fteqw than anything

**Comment by Nolcoz** [comment]
Updated the map to hopefully fix the fteqw problems, among some other small changes

**Comment by lavenderdotpet** [comment]
image

**Comment by Nolcoz** [comment]
Gonna be honest on my screen I only see a black void. On my phone screen I can see it a lil more but not by much. Maybe its a britghness thing?
Even then I wanna try to not add more geometry to the open are, because how already big it is, which makes the vertices add up

**Comment by lavenderdotpet** [comment]
might if I try out an idea on Ur map

**Comment by Nolcoz** [comment]
Sure, ye

**Comment by Zungrysoft** [comment]
I'll try to give this a second playthrough and a review either today or tomorrow.

**Review by Zungrysoft — APPROVED** [review]

**Comment by Zungrysoft** [comment]
@Nolcoz Make sure to update the rune to the Episode 3 rune.

**Comment by Nolcoz** [comment]
Updated the rune so its the episode 3 one now

**Comment by lavenderdotpet** [comment]
> might if I try out an idea on Ur map

this will be done in its own pull req later on

**Review by lavenderdotpet — APPROVED** [review]

**Pull request merged**
