### PR TITLE
e0m2: Small tweaks

### PR DESCRIPTION
**Pull request by RandomBrushes**
### Description of Changes
---
- added some geometry on a ceiling
- texture alignment tweaks
- turned a time-based trigger into a trigger brush

Latter is the only gameplay-related change and serves to avoid player-confusion on why suddenly there are knights rushing in.

### Visual Sample
spasm0000
spasm0001

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Review by Nolcoz — APPROVED** [review]
Looks good and had no issue testing it

**Review by MotoLegacy — APPROVED** [review]
Looks good to me, thanks!

**Comment by MotoLegacy** [comment]
Please let us know when you are comfortable with a merge.

**Comment by RandomBrushes** [comment]
> Please let us know when you are comfortable with a merge.

well, I am ;-)

**Pull request merged**
