### PR TITLE
AUDIO: Added remaining brush entity sound effects

### PR DESCRIPTION
**Pull request by Zungrysoft**
### Description of Changes
---
Adds all of the remaining brush entity sounds:
- `buttons/airbut1.wav` - Steam Metal button.
- `doors/airdoor1.wav` - Metal secret door move. (Old sound was moved to `doors/basesec1.wav`)
- `doors/airdoor2.wav` - Metal secret door stop. (Old sound was moved to `doors/basesec2.wav`)
- `doors/doormv1.wav` - Stone door move.
- `doors/drclos4.wav` - Stone door and medieval secret door stop.
- `doors/latch2.wav` - Medieval secret door start. (This is unused due to a bug in the progs.dat)
- `doors/stndr1.wav` - Stone Chain door move.
- `doors/stndr2.wav` - Stone Chain door stop.
- `doors/winch2.wav` - Medieval secret door move. (Modified the previous sound with new EQ and fixed looping.)
- `misc/trigger1.wav` - Large Switch trigger sound.
- `plats/medplat1.wav` - Chain Slow lift move.
- `plats/medplat2.wav` - Chain Slow lift stop.
- `plats/train1.wav` - Train move. (Duplicate of `doors/winch2.wav`)
- `plats/train2.wav` - Train stop.

### Visual Sample
---
https://github.com/user-attachments/assets/0dc9509e-085f-4e92-a5e2-c887c441e892

### Checklist
---

- [x] I have read the LibreQuake contribution guidelines
- [x] I have thoroughly tested my changes to the best of my ability
- [x] I confirm I have not contributed anything that would impact LibreQuake's licensing and usage
- [ ] This Pull Request fixes a **critical** issue that should be reviewed and merged as soon as possible

### CODE REVIEW

**Comment by lavenderdotpet** [comment]
make sure to add Ur credits to the meta data

**Comment by Zungrysoft** [comment]
> make sure to add Ur credits to the meta data

I can't figure out how to add metadata to a wav file without destroying loop points. I need to use Wavosaur to add loop points, but it ends up removing the metadata in the process.

**Comment by lavenderdotpet** [comment]
> > make sure to add Ur credits to the meta data
> 
> I can't figure out how to add metadata to a wav file without destroying loop points. I need to use Wavosaur to add loop points, but it ends up removing the metadata in the process. Audacity can add the metadata, but it removes the loop points.

are there any sounds here that don't require loop points

**Comment by Nolcoz** [comment]
>I can't figure out how to add metadata to a wav file without destroying loop points. I need to use Wavosaur to add loop points, but it ends up removing the metadata in the process. Audacity can add the metadata, but it removes the loop points.

Oceanaudio does allow you to both put loop points and also metadata if you wanna check that

**Comment by Zungrysoft** [comment]
Oh shoot. I fucked something up.

**Review by Nolcoz — APPROVED** [review]
Looking good ye

**Review by lavenderdotpet — APPROVED** [review]

**Pull request merged**
